##
#  This file is part of 07-ticktacktoe task.
#
#  Makefile
#  Stanisław Grams <sgrams@fmdx.pl>
##

CC=gcc
CFLAGS=-Wall -Werror
LDFLAGS=-lncurses
OUTNAME=game

all: main
main: main.c

clean:
	rm -f $(OUTNAME)
